# Generated by Django 4.2.7 on 2025-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="The MIMEType of the file",
                max_length=256,
                null=True,
            ),
        ),
    ]
