# Generated by Django 4.2.7 on 2025-03-19 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0003_fav_recipe_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fav",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favs_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
